### ISSUE TITLE
message.frm from callback_message not working completely when passed to send

### ISSUE THREAD

**Issue by DrWaluigi** [gbin/err#529] opened 2015-11-02 20:40 UTC
Hi,

I'm currently using Errbot 3.1.1 on ArchLinux and there seems to be a problem around (my use of?) the frm attribute of a message object.

In a plugin, I use the message.frm from a callback (*callback_message*) and pass it directly to the *send* function. It's working perfectly in private chat with the bot, but it doesn't work in muc.

The message object from the callback has a frm formed like this for muc : *muc@conference.domain.tld/user*
It seems that the send function doesn't work correctly with the /user, because if I strip the /user it kinda works (but the bot reacts to his own messages and spam the muc, only in muc, not in private chat).

Am I doing something wrong ? Is this a bug in Err ? If yes, is there any way I can help you to resolve this problem ?

**Comment by zoni** [comment] 2015-11-02 21:44
`muc@conference.domain.tld/user` is a valid JID for a MUC occupant, so that should work and you should be able to pass it on directly to `send()`.

Are you perhaps not passing `type="groupchat"` when you call send like this?

**Comment by DrWaluigi** [comment] 2015-11-02 22:17
Thank you for your response !

For the type, I was repassing the type from the received message, so if I'm not wrong, for messages from groupchat, the type is already groupchat ?

I've just tried with a minimal plugin (just resend each message received) : 
```python
from errbot import BotPlugin                                            

class LinksBot(BotPlugin):
    
    min_err_version = '3.1.1'
    max_err_version = '3.1.1'
    
    def callback_message(self, message):
        
        self.log.info(message.frm)
        self.log.info(message.body)
        self.log.info(message.type)
        
        self.send(message.frm,
                  message.body,
                  message_type=message.type)
```

It works for private conversations, but not in muc.

Here are the logs of the plugin for the private test (inversed order) : 
```
chat
testmessage
user@domain.tld/resource
```

Here are the logs of the plugin for the muc test (inversed order) : 
```
groupchat
testmessage
muc@conference.domain.tld/user
```

Am I doing something wrong?

**Comment by zoni** [comment] 2015-11-03 17:41
No, I don't think you're doing anything wrong. That looks all right, at any rate.

I need to run Err against a real XMPP server and see what's going on, but I don't have a server to test against right now so it may take me a couple before I'll get to that.

**Comment by Kromey** [comment] 2015-11-04 23:42
I was running into the same issue in MUC; in my case, I was able to work around it with
`self.send(self.build_identifier(msg.frm.person) ...)`
which is, of course, a pretty awkward construction. (Note: I have not yet tried to build the identifier from `msg.frm` directly.)

It seems to me that the object returned by the Message.frm property, whether in MUC or direct chat, should be directly usable in `self.send()`.

**Comment by gbin** [comment] 2015-11-05 00:34
just tested it on master, and it works privately and in a chatroom, both frm on a command and on a callback_message:

```
  @botcmd
  def test_frm(self, mess, args):
    self.log.debug(mess.frm)
    self.send(mess.frm, 'echo: ' + mess.body, message_type=mess.type)

  def callback_message(self, mess):
    self.log.debug(mess.frm)
    self.send(mess.frm, 'echo cb: ' + mess.body, message_type=mess.type)
```
 ... I am puzzled:

```
16:31:06 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: message
16:31:06 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: groupchat_message
16:31:06 DEBUG    sleekxmpp.xmlstream.xmlst Event triggered: muc::errbot@rooms.blah.im::message
16:31:06 DEBUG    errbot.backends.xmpp      incoming_message frm : errbot@rooms.blah.im/err
16:31:06 DEBUG    errbot.backends.xmpp      incoming_message frm node: errbot
16:31:06 DEBUG    errbot.backends.xmpp      incoming_message frm domain: rooms.blah.im
16:31:06 DEBUG    errbot.backends.xmpp      incoming_message frm resource: err
16:31:06 DEBUG    errbot.errBot             *** frm = errbot@rooms.blah.im/err
16:31:06 DEBUG    errbot.errBot             *** username = errbot@rooms.blah.im/err
16:31:06 DEBUG    errbot.errBot             *** type = groupchat
16:31:06 DEBUG    errbot.errBot             *** text = echo: !test frm
16:31:06 DEBUG    errbot.errBot             Trigger callback_message on Utils
16:31:06 DEBUG    errbot.errBot             Trigger callback_message on ChatRoom
16:31:06 DEBUG    errbot.errBot             Trigger callback_message on BotTest
16:31:06 DEBUG    errbot.plugins.BotTest    errbot@rooms.blah.im/err
16:31:06 DEBUG    errbot.errBot             Trigger callback_message on TimeBot
16:31:06 DEBUG    sleekxmpp.xmlstream.xmlst SEND: <message xml:lang="en" type="groupchat" to="errbot@rooms.blah.im"><body>echo cb: echo: !test frm</body></message>
16:31:06 DEBUG    errbot.errBot             Trigger callback_message on Backup
16:31:06 DEBUG    errbot.errBot             Trigger callback_message on Health
16:31:06 DEBUG    errbot.errBot             Trigger callback_message on Help
16:31:06 DEBUG    errbot.errBot             Trigger callback_message on VersionChecker
16:31:06 DEBUG    errbot.errBot             Trigger callback_message on Plugins
16:31:06 DEBUG    errbot.errBot             Trigger callback_message on Webserver
16:31:06 DEBUG    errbot.errBot             Trigger callback_message on ACLS
16:31:06 DEBUG    sleekxmpp.xmlstream.xmlst RECV: <message from="errbot@rooms.blah.im/err" xml:lang="en" type="groupchat" to="err@blah.im/b199f097-e587-40a0-a0e8-7d0a3d092dcb"><body>echo cb: !test frm</body></message>
````

**Comment by Kromey** [comment] 2015-11-05 01:44
Did some further testing (a 3.1.1 installed from PyPi) myself with a very similar test command to your @gbin, but my results differ: worked fine in one-on-one, but not in MUC (snipped callback_message logs for brevity):

```
2015-11-04 16:29:16,385 DEBUG    sleekxmpp.xmlstream.xmlstream RECV: <message id="purple734ce074" type="groupchat" to="testbot@fairbanksnano.org/errbot" from="test@conf.fairbanksnano.org/kromey"><body>testbot test frm</body></message>
2015-11-04 16:29:16,386 DEBUG    sleekxmpp.xmlstream.xmlstream Event triggered: message
2015-11-04 16:29:16,386 DEBUG    sleekxmpp.xmlstream.xmlstream Event triggered: groupchat_message
2015-11-04 16:29:16,387 DEBUG    sleekxmpp.xmlstream.xmlstream Event triggered: muc::test@conf.fairbanksnano.org::message
2015-11-04 16:29:16,387 DEBUG    errbot.backends.xmpp      incoming_message frm : test@conf.fairbanksnano.org/kromey
2015-11-04 16:29:16,387 DEBUG    errbot.backends.xmpp      incoming_message frm node: test
2015-11-04 16:29:16,387 DEBUG    errbot.backends.xmpp      incoming_message frm domain: conf.fairbanksnano.org
2015-11-04 16:29:16,388 DEBUG    errbot.backends.xmpp      incoming_message frm resource: kromey
2015-11-04 16:29:16,388 DEBUG    errbot.errBot             *** frm = test@conf.fairbanksnano.org/kromey
2015-11-04 16:29:16,388 DEBUG    errbot.errBot             *** username = test@conf.fairbanksnano.org/kromey
2015-11-04 16:29:16,388 DEBUG    errbot.errBot             *** type = groupchat
2015-11-04 16:29:16,388 DEBUG    errbot.errBot             *** text = testbot test frm 
2015-11-04 16:29:16,389 DEBUG    errbot.errBot             Called with alternate prefix 'testbot'
2015-11-04 16:29:16,389 INFO     errbot.plugins.ACLS       Check test_frm for ACLs.
2015-11-04 16:29:16,389 INFO     errbot.plugins.ACLS       Check if test_frm is admin only command.
2015-11-04 16:29:16,389 INFO     errbot.errBot             Processing command 'test_frm' with parameters '' from test@conf.fairbanksnano.org/kromey
2015-11-04 16:29:16,390 INFO     errbot.plugins.WarBot     Message from: test@conf.fairbanksnano.org/kromey
2015-11-04 16:29:16,391 DEBUG    sleekxmpp.xmlstream.xmlstream SEND: <message xml:lang="en" type="groupchat" to="test@conf.fairbanksnano.org/kromey"><body>This is a test of self.send(msg.frm...)</body></message>
2015-11-04 16:29:16,394 DEBUG    sleekxmpp.xmlstream.xmlstream RECV: <message type="error" to="testbot@fairbanksnano.org/errbot" from="test@conf.fairbanksnano.org/kromey"><error type="modify"><bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas" /></error></message>
2015-11-04 16:29:16,396 DEBUG    sleekxmpp.xmlstream.xmlstream Event triggered: groupchat_message_error
2015-11-04 16:29:16,396 DEBUG    sleekxmpp.xmlstream.xmlstream Event triggered: muc::test@conf.fairbanksnano.org::message_error
```

Note the last 3 lines indicating an error, specifically `bad-request xmlns="urn:ietf:params:xml:ns:xmpp-stanzas"` -- which I don't have the foggiest what it means, that's getting way too into the nitty-gritty details of XMPP for me!

I notice that your MUC message seems to be stripping off the "resource" (`...SEND: <message xml:lang="en" type="groupchat" to="errbot@rooms.blah.im">...`), while mine is not (`...SEND: <message xml:lang="en" type="groupchat" to="test@conf.fairbanksnano.org/kromey">...`). This seems to be consistent with my solution, as `Message.frm.person` strips off the "resource" part, and then I pass that over to `self.build_identifier()` before using it in `self.send()`.

So it looks like at some point a change to `self.send()` was made in master that is stripping off that resource (perhaps only in MUC?), and that change isn't in 3.1.1.

**Comment by zoni** [comment] 2015-11-05 08:01
So as part of #534 I actually made a small change to `self.send()`, which was calling `build_identifier` even when already given an identifier. It's in commit 333cfbe29be0f7510d0815ee239c22a01c86e9fa.

*maybe* we have the same issue here. It may be worth trying it out with that branch checked out.

**Comment by gbin** [comment] 2015-11-05 17:22
ha yeah, this was weird...  we were doing a tostr / build identifier everytime.
So this is one bug, I gonna cherry-pick it. But then we have another one, we need to have unittests on every backend that do identifier -> str -> identifier and check if we keep getting the same one

**Comment by gbin** [comment] 2015-11-05 17:27
... but this is not our issue because it works on head.

**Comment by gbin** [comment] 2015-11-05 17:58
Ho ok, now I understand fully, this is linked to a change we also made on compat_str

master
```
def compat_str(s):
    """ Detect if s is a string and convert it to unicode if it is a byte or
        py2 string
        :param s: the string to ensure compatibility from."""
    if isinstance(s, str):
        return s
    elif isinstance(s, bytes):
        return s.decode('utf-8')
    else:
        return str(s)
```

3.1
```
def compat_str(s):
    """ Detect if s is a string and convert it to unicode if it is a byte or
        py2 string """
    if isinstance(s, str):
        return s
    elif isinstance(s, bytes):
        return s.decode()
    return None
```

So basically if you pass an identifier on master, it will try to stringify it and succeed:
```
# in send
[...]
s = compat_str(user)
  if s is not None:
    user = self.build_identifier(s)
```
If you do the same thing on 3.1, it will be None.

**Comment by zoni** [comment] 2015-11-05 20:04
I believe I did that in 4ed92ff24bf3c7917c9f46b88d800a144aaaaf24.

So it looks like this is definitely fixed in master then (@Kromey, @DrWaluigi , an either of you confirm?).

May be worth releasing a 3.1.2 soon.

**Comment by gbin** [comment] 2015-11-05 20:10
@zoni the root of the problem is that frm is room@rooms.service.com/user and type 'groupchat'.
But when you answer a message on XMPP you need to change it to:
room@rooms.service.com type 'groupchat'
or room@rooms.service.com/user type `chat' 

This is totally xmpp specific, the fix needs to be done in the XMPP backend otherwise this will regress other backends: basically the fix is if 'groupchat' remove resource.

**Comment by gbin** [comment] 2015-11-05 22:01
fixed by 8da1b39d04db08cbecc64b0e29c5d45b5cdd6de7 on master
and 52dfef31e59621a6991d7aec862cd52afc0afa85  on 3.1

**Closed by gbin** 2015-11-05 22:01 UTC

**Comment by DrWaluigi** [comment] 2015-11-08 11:16
Sorry for the delay, I was unavailable. Now it's working, thank you ! But the bot reacts to its own messages, and I think that it wasn't the case some months ago. Is it normal ?

**Comment by gbin** [comment] 2015-11-08 22:56
Nope I noticed that on a couple other backends, please file à séparateur bug for this, all thé backends should have a mechanism to recognize messages from self :) meanwhile you can start a competition to fine a quine with err-codebot :)
